### PR TITLE
[ISDK-18] Assessment Listing

### PR DESCRIPTION
**Pull request by imkven**
https://intersective.atlassian.net/browse/ISDK-18

### CODE REVIEW

**Comment by beenishs** [comment]
HI @imkven, In the files I can see PE specific files?

**Comment by jazzmind** [comment]
@imkven  pls remove those img/font files and also fix conflicts, thanks!

**Comment by imkven** [comment]
@jazzmind I has removed all img/font related to PE.

**Comment by trtshen** [comment]
@imkven please be careful when you remove awesome-font, we have code here [dedicated format-based icons](https://github.com/intersective/practera-sdk-ionic/blob/master/src/theme/utils.scss#L129-L145) are using the awesome-font as in the event attachment list page and file upload assessment.

**Comment by imkven** [comment]
@trtshen Thank for note. FYI, we no remove `awesome-font`, it just moved to `practera.theme.default.scss` from `core.scss`. Since you said, we have used it on `utils.scss`, do we need move back to `core.scss`?

**Pull request merged**
